# A list of site channels which require manual admin approval in addition to the
# standard verification flow.

- "facebook.com"
- "twitter.com"
- "google.com"
- "youtube.com"
- "instagram.com"
- "linkedin.com"
- "wordpress.org"
- "pinterest.com"
- "wikipedia.org"
- "wordpress.com"
- "blogspot.com"
- "apple.com"
- "adobe.com"
- "tumblr.com"
- "youtu.be"
- "amazon.com"
- "goo.gl"
- "vimeo.com"
- "flickr.com"
- "microsoft.com"
- "yahoo.com"
- "bit.ly"
- "vk.com"
- "godaddy.com"
- "reddit.com"
- "qq.com"
- "buydomains.com"
- "w3.org"
- "nytimes.com"
- "t.co"
- "europa.eu"
- "statcounter.com"
- "weebly.com"
- "blogger.com"
- "wp.com"
- "jimdo.com"
- "bbc.co.uk"
- "soundcloud.com"
- "github.com"
- "yandex.ru"
- "myspace.com"
- "mozilla.org"
- "gravatar.com"
- "baidu.com"
- "google.de"
- "addthis.com"
- "theguardian.com"
- "google.co.jp"
- "nih.gov"
- "cnn.com"
- "stumbleupon.com"
- "paypal.com"
- "digg.com"
- "wix.com"
- "creativecommons.org"
- "huffingtonpost.com"
- "imdb.com"
- "issuu.com"
- "feedburner.com"
- "yelp.com"
- "miitbeian.gov.cn"
- "bluehost.com"
- "addtoany.com"
- "dropbox.com"
- "amazonaws.com"
- "google.co.uk"
- "forbes.com"
- "parallels.com"
- "wixsite.com"
- "washingtonpost.com"
- "go.com"
- "msn.com"
- "etsy.com"
- "wsj.com"
- "slideshare.net"
- "archive.org"
- "eventbrite.com"
- "ameblo.jp"
- "mail.ru"
- "telegraph.co.uk"
- "fc2.com"
- "amazon.co.uk"
- "sourceforge.net"
- "ebay.com"
- "livejournal.com"
- "doubleclick.net"
- "free.fr"
- "e-recht24.de"
- "dailymail.co.uk"
- "reuters.com"
- "bloomberg.com"
- "typepad.com"
- "amzn.to"
- "yahoo.co.jp"
- "miibeian.gov.cn"
- "wikimedia.org"
- "cpanel.net"
- "about.com"
- "eepurl.com"
- "usatoday.com"
- "macromedia.com"
- "cpanel.com"
- "bing.com"
- "time.com"
- "amazon.de"
- "hatena.ne.jp"
- "elegantthemes.com"
- "cdc.gov"
- "constantcontact.com"
- "weibo.com"
- "npr.org"
- "google.it"
- "aol.com"
- "harvard.edu"
- "www.gov.uk"
- "tripadvisor.com"
- "xing.com"
- "latimes.com"
- "webs.com"
- "blogspot.co.uk"
- "bbb.org"
- "icio.us"
- "medium.com"
- "list-manage.com"
- "live.com"
- "amazon.co.jp"
- "bandcamp.com"
- "opera.com"
- "namejet.com"
- "apache.org"
- "dailymotion.com"
- "51.la"
- "bbc.com"
- "businessinsider.com"
- "mit.edu"
- "gnu.org"
- "vkontakte.ru"
- "rambler.ru"
- "behance.net"
- "guardian.co.uk"
- "surveymonkey.com"
- "disqus.com"
- "taobao.com"
- "github.io"
- "google.es"
- "stanford.edu"
- "joomla.org"
- "wired.com"
- "1und1.de"
- "kickstarter.com"
- "google.fr"
- "spotify.com"
- "nasa.gov"
- "delicious.com"
- "ted.com"
- "independent.co.uk"
- "goodreads.com"
- "google.ca"
- "domainactive.co"
- "geocities.com"
- "googleusercontent.com"
- "homestead.com"
- "imgur.com"
- "cnet.com"
- "photobucket.com"
- "scribd.com"
- "rakuten.co.jp"
- "line.me"
- "deviantart.com"
- "tripod.com"
- "one.com"
- "ca.gov"
- "themeforest.net"
- "domainname.de"
- "wiley.com"
- "un.org"
- "who.int"
- "barnesandnoble.com"
- "pbs.org"
- "beian.gov.cn"
- "nationalgeographic.com"
- "theatlantic.com"
- "buzzfeed.com"
- "shopify.com"
- "cbsnews.com"
- "networksolutions.com"
- "foxnews.com"
- "blogspot.com.es"
- "domainretailing.com"
- "techcrunch.com"
- "nature.com"
- "sakura.ne.jp"
- "webmd.com"
- "berkeley.edu"
- "ibm.com"
- "mashable.com"
- "trustpilot.com"
- "cloudfront.net"
- "sciencedirect.com"
- "php.net"
- "sina.com.cn"
- "getpocket.com"
- "nbcnews.com"
- "booking.com"
- "whitehouse.gov"
- "cornell.edu"
- "usda.gov"
- "wp.me"
- "squarespace.com"
- "skype.com"
- "change.org"
- "a8.net"
- "cbc.ca"
- "noaa.gov"
- "hostnet.nl"
- "ft.com"
- "epa.gov"
- "meetup.com"
- "springer.com"
- "blogspot.ca"
- "plesk.com"
- "domraider.io"
- "secureserver.net"
- "nps.gov"
- "blogspot.de"
- "myshopify.com"
- "ow.ly"
- "wikia.com"
- "phoca.cz"
- "mapquest.com"
- "enable-javascript.com"
- "usnews.com"
- "naver.com"
- "phpbb.com"
- "cnbc.com"
- "jiathis.com"
- "google.nl"
- "foursquare.com"
- "loc.gov"
- "economist.com"
- "google.com.br"
- "uol.com.br"
- "wufoo.com"
- "fda.gov"
- "spiegel.de"
- "chicagotribune.com"
- "sfgate.com"
- "irs.gov"
- "list-manage1.com"
- "bigcartel.com"
- "newyorker.com"
- "bizjournals.com"
- "abc.net.au"
- "prnewswire.com"
- "slate.com"
- "cbslocal.com"
- "umblr.com"
- "hp.com"
- "geocities.jp"
- "gizmodo.com"
- "marriott.com"
- "ed.gov"
- "dribbble.com"
- "livedoor.jp"
- "doi.org"
- "nydailynews.com"
- "engadget.com"
- "about.me"
- "vice.com"
- "4.cn"
- "google.com.au"
- "state.gov"
- "storify.com"
- "telegram.me"
- "umich.edu"
- "fb.com"
- "fortune.com"
- "nifty.com"
- "houzz.com"
- "unesco.org"
- "histats.com"
- "clickbank.net"
- "1and1.com"
- "mijndomein.nl"
- "ok.ru"
- "themegrill.com"
- "house.gov"
- "loopia.se"
- "globo.com"
- "1and1.fr"
- "loopia.com"
- "visma.com"
- "indiegogo.com"
- "163.com"
- "columbia.edu"
- "yale.edu"
- "rs6.net"
- "ocn.ne.jp"
- "linksynergy.com"
- "wunderground.com"
- "academia.edu"
- "washington.edu"
- "sciencedaily.com"
- "google.pl"
- "upenn.edu"
- "hilton.com"
- "theverge.com"
- "weather.com"
- "gofundme.com"
- "businessweek.com"
- "biglobe.ne.jp"
- "debian.org"
- "aboutcookies.org"
- "feedly.com"
- "fb.me"
- "goo.ne.jp"
- "oup.com"
- "ustream.tv"
- "psychologytoday.com"
- "blogspot.in"
- "nypost.com"
- "samsung.com"
- "senate.gov"
- "marketwatch.com"
- "elpais.com"
- "android.com"
- "indiatimes.com"
- "dreamhost.com"
- "scientificamerican.com"
- "fastcompany.com"
- "oracle.com"
- "wikihow.com"
- "theglobeandmail.com"
- "mailchimp.com"
- "studiopress.com"
- "whatsapp.com"
- "home.pl"
- "zdnet.com"
- "sagepub.com"
- "athemes.com"
- "smh.com.au"
- "ucla.edu"
- "businesswire.com"
- "cdbaby.com"
- "umn.edu"
- "fbcdn.net"
- "wisc.edu"
- "ftc.gov"
- "drupal.org"
- "psu.edu"
- "utexas.edu"
- "directdomains.com"
- "ox.ac.uk"
- "researchgate.net"
- "tripadvisor.co.uk"
- "hbr.org"
- "entrepreneur.com"
- "sohu.com"
- "xinhuanet.com"
- "sciencemag.org"
- "inc.com"
- "exblog.jp"
- "sedo.com"
- "google.co.in"
- "mozilla.com"
- "shinystat.com"
- "youronlinechoices.com"
- "walmart.com"
- "cryoutcreations.eu"
- "quora.com"
- "tucowsdomains.com"
- "worldbank.org"
- "newsweek.com"
- "prweb.com"
- "shareasale.com"
- "jugem.jp"
- "allaboutcookies.org"
- "si.edu"
- "mirror.co.uk"
- "tandfonline.com"
- "census.gov"
- "target.com"
- "usgs.gov"
- "rollingstone.com"
- "princeton.edu"
- "nymag.com"
- "stackoverflow.com"
- "hubspot.com"
- "networkadvertising.org"
- "arstechnica.com"
- "nazwa.pl"
- "liveinternet.ru"
- "intel.com"
- "politico.com"
- "lemonde.fr"
- "campaign-archive1.com"
- "seesaa.net"
- "campaign-archive2.com"
- "amazon.fr"
- "mysql.com"
- "cam.ac.uk"
- "hibu.com"
- "cisco.com"
- "nyu.edu"
- "alexa.com"
- "smugmug.com"
- "hhs.gov"
- "accuweather.com"
- "zendesk.com"
- "presscustomizr.com"
- "hollywoodreporter.com"
- "archives.gov"
- "shop-pro.jp"
- "box.com"
- "t.me"
- "uchicago.edu"
- "hostgator.com"
- "google.ru"
- "nhk.or.jp"
- "example.com"
- "admin.ch"
- "bls.gov"
- "variety.com"
- "oxfordjournals.org"
- "ebay.co.uk"
- "teamviewer.com"
- "bmj.com"
- "youku.com"
- "acquirethisname.com"
- "office.com"
- "netflix.com"
- "alibaba.com"
- "redcross.org"
- "oecd.org"
- "list-manage2.com"
- "eventbrite.co.uk"
- "usc.edu"
- "wsimg.com"
- "va.gov"
- "colorlib.com"
- "ap.org"
- "cmu.edu"
- "domainnameshop.com"
- "apa.org"
- "mlb.com"
- "sogou.com"
- "xiti.com"
- "istockphoto.com"
- "t-online.de"
- "www.nhs.uk"
- "dropboxusercontent.com"
- "people.com.cn"
- "prestashop.com"
- "ieee.org"
- "cafepress.com"
- "blogspot.jp"
- "twitch.tv"
- "domeneshop.no"
- "opensource.org"
- "dell.com"
- "zenfolio.com"
- "22.cn"
- "livestream.com"
- "icann.org"
- "vox.com"
- "unc.edu"
- "nsw.gov.au"
- "staticflickr.com"
- "openstreetmap.org"
- "dot.gov"
- "usa.gov"
- "umd.edu"
- "qz.com"
- "google.ch"
- "purdue.edu"
- "att.com"
- "adweek.com"
- "thehill.com"
- "fao.org"
- "hud.gov"
- "com.com"
- "state.tx.us"
- "nginx.org"
- "army.mil"
- "ewebdevelopment.com"
- "woocommerce.com"
- "duke.edu"
- "venturebeat.com"
- "justgiving.com"
- "mtv.com"
- "today.com"
- "steampowered.com"
- "symantec.com"
- "enom.com"
- "sun.com"
- "netscape.com"
- "biomedcentral.com"
- "fotolia.com"
- "gpo.gov"
- "dictionary.com"
