# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  admin_ip_whitelist: <%= ENV["ADMIN_IP_WHITELIST"] %>
  # (Optional) Token required to use this app's API.
  api_auth_token: <%= ENV["API_AUTH_TOKEN"] %>
  # (Optional) Comma separated list of IPs or CIDR strings e.g. ::1,127.0.0.1/16,1.2.3.4/32
  api_ip_whitelist: <%= ENV["API_IP_WHITELIST"] %>
  # Eyeshade API used for PublisherTokenRequester
  api_eyeshade_base_uri: <%= ENV["API_EYESHADE_BASE_URI"] %>
  api_legacy_eyeshade_base_uri: <%= ENV["API_LEGACY_EYESHADE_BASE_URI"] %>
  api_eyeshade_key: <%= ENV["API_EYESHADE_KEY"] %>
  api_legacy_eyeshade_key: <%= ENV["API_LEGACY_EYESHADE_KEY"] %>
  # Use offline non-canonical implementation of eyeshade API.
  api_eyeshade_offline: <%= ENV["API_EYESHADE_BASE_URI"].blank? %>
  attr_encrypted_key: <%= ENV["ATTR_ENCRYPTED_KEY"] %>
  # Optional. If present protects the app with HTTP Basic Auth.
  basic_auth_password: <%= ENV["BASIC_AUTH_PASSWORD"] %>
  basic_auth_user: <%= ENV["BASIC_AUTH_USER"] %>
  internal_email: <%= ENV["INTERNAL_EMAIL"] %>
  # Piwik analytics endpoint with trailing slash e.g. https://piwik.example.com/
  piwik_host: <%= ENV["PIWIK_HOST"] %>
  proxy_url: <%= ENV["PROXY_URL"] %>
  #SMTP Mailer settings
  smtp_server_port: <%= ENV["MAILGUN_SMTP_PORT"] %>
  smtp_server_address: <%= ENV["MAILGUN_SMTP_SERVER"] %>
  smtp_server_login: <%= ENV["MAILGUN_SMTP_LOGIN"] %>
  smtp_server_password: <%= ENV["MAILGUN_SMTP_PASSWORD"] %>
  mailer_sender: <%= ENV["MAILER_SENDER"] %>
  redis_url: <%= ENV["REDIS_URL"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  support_email: <%= ENV["SUPPORT_EMAIL"] %>
  from_email: <%= ENV["FROM_EMAIL"] %>
  # e.g. #devops-bot
  slack_channel_diagnostic: <%= ENV["SLACK_CHANNEL_DIAGNOSTIC"] %>
  slack_webhook_url: <%= ENV["SLACK_WEBHOOK_URL"] %>
  # e.g. publishers.brave.com
  url_host: <%= ENV["URL_HOST"] %>
  uphold_authorization_endpoint: <%= ENV["UPHOLD_AUTHORIZATION_ENDPOINT"] %>
  uphold_dashboard_url: <%= ENV["UPHOLD_DASHBOARD_URL"] %>
  uphold_client_id: <%= ENV["UPHOLD_CLIENT_ID"] %>
  uphold_client_secret: <%= ENV["UPHOLD_CLIENT_SECRET"] %>
  uphold_api_uri: <%= ENV["UPHOLD_API_URI"] %>
  uphold_scope: <%= ENV["UPHOLD_SCOPE"] %>
  # Use offline mode of publisher host inspector
  host_inspector_offline: <%= ENV["HOST_INSPECTOR_OFFLINE"] %>
  terms_of_service_url: <%= ENV["TERMS_OF_SERVICE_URL"] %>
  google_client_id: <%= ENV["GOOGLE_CLIENT_ID"] %>
  google_client_secret: <%= ENV["GOOGLE_CLIENT_SECRET"] %>
  twitch_client_id: <%= ENV["TWITCH_CLIENT_ID"] %>
  twitch_client_secret: <%= ENV["TWITCH_CLIENT_SECRET"] %>
  # Social media links
  bat_medium_url: <%= ENV["BAT_MEDIUM_URL"] %>
  bat_twitter_url: <%= ENV["BAT_TWITTER_URL"] %>
  bat_reddit_url: <%= ENV["BAT_REDDIT_URL"] %>
  bat_rocketchat_url: <%= ENV["BAT_ROCKETCHAT_URL"] %>
  log_api_requests: <%= ENV["LOG_API_REQUESTS"] %>
  log_verbose: <%= ENV["LOG_VERBOSE"] %>
  default_api_page_size: <%= ENV["DEFAULT_API_PAGE_SIZE"] %>
  # Promo API used by PromoRegistrar
  api_promo_base_uri: <%= ENV["API_PROMO_BASE_URI"] %>
  api_promo_key: <%= ENV["API_PROMO_KEY"] %>
  active_promo_id: <%= ENV["ACTIVE_PROMO_ID"] %>
  base_referral_url: <%= ENV["BASE_REFERRAL_URL"] %>
  max_site_age: <%= ENV["MAX_SITE_AGE"] %> # Maximimum age in weeks of sites enqueued for verification
  should_send_notifications: <%= ENV["SHOULD_SEND_NOTIFICATIONS"] %> # Enables eyeshade notifications
  # Sendgrid
  sendgrid_api_key: <%= ENV["SENDGRID_API_KEY"] %>
  sendgrid_api_offline: <%= ENV["SENDGRID_API_KEY"].blank? %>
  sendgrid_publishers_list_id: <%= ENV["SENDGRID_PUBLISHERS_LIST_ID"] %>
  # Hide FAQ links
  hide_faqs: <%= ENV["HIDE_FAQS"] %>

development:
  <<: *default
  api_promo_base_uri: "" # http://127.0.0.1:8194
  active_promo_id: "free-bats-2018q1"
  base_referral_url: "brave.com"
  internal_email: brave-publishers@localhost.local
  support_email: brave-publishers@localhost.local
  from_email: Brave Payments Publishers Dev<brave-publishers@localhost.local>
  attr_encrypted_key: 499a4c51df667b4edfab40c1f8b813b7ed6ce02096d59f23b5dcb095369375f6
  secret_key_base: dd7b12788a804315fd75f1ff97fae33310b451c39d83d1d015543d25d0ba034c02fd312e83735f0d0aeaaf70131f26e614629e3c40531b949445b4dfacd3bad3
  uphold_authorization_endpoint: <%= ENV["UPHOLD_AUTHORIZATION_ENDPOINT"] || "https://sandbox.uphold.com/authorize/<UPHOLD_CLIENT_ID>?scope=<UPHOLD_SCOPE>&intention=signup&state=<STATE>" %>
  uphold_client_id: <%= ENV["UPHOLD_CLIENT_ID"] || "test_client_id" %>
  uphold_client_secret: <%= ENV["UPHOLD_CLIENT_SECRET"] || "test_client_secret" %>
  uphold_scope: <%= ENV["UPHOLD_SCOPE"] || "cards:read,cards:write,user:read" %>
  uphold_api_uri: <%= ENV["UPHOLD_API_URI"] || "https://api-sandbox.uphold.com" %>
  uphold_dashboard_url: <%= ENV["UPHOLD_DASHBOARD_URL"] || "https://sandbox.uphold.com/dashboard" %>
  # Social media links
  bat_medium_url: "https://medium.com/@attentiontoken"
  bat_twitter_url: "https://twitter.com/@attentiontoken"
  bat_reddit_url: "https://www.reddit.com/r/BATProject/"
  bat_rocketchat_url: "https://basicattentiontoken.rocket.chat/"
  max_site_age: 6
  should_send_notifications: true
  slack_webhook_url: false

test:
  <<: *default
  admin_ip_whitelist: "127.0.0.1"
  api_promo_base_uri: "" # http://127.0.0.1:8194
  active_promo_id: "free-bats-2018q1"
  api_auth_token: "fake_api_auth_token"
  api_eyeshade_base_uri: http://127.0.0.1:8194
  api_eyeshade_offline: true
  host_inspector_offline: true
  api_eyeshade_key: fakeapikey123
  internal_email: brave-publishers@localhost.local
  support_email: brave-publishers@localhost.local
  from_email: Brave Payments Publishers Test<brave-publishers@localhost.local>
  attr_encrypted_key: 44c101d4dab61a9aa6f13ebd63ad361ba79567604c6ac8bb68e0874d9cf84f05
  secret_key_base: 2a6a0e458f1a3513655583c806f654e0b2be3dac10be16cad9562c089384cb968f30a9774f7ed247e95d48d51f21d69edeab89b95d140a1007bae21621b284f8
  uphold_authorization_endpoint: "https://uphold.example.com/authorize/<UPHOLD_CLIENT_ID>?scope=<UPHOLD_SCOPE>&intention=signup&state=<STATE>"
  uphold_client_id: test_client_id
  uphold_client_secret: test_client_secret
  uphold_scope: cards:read,cards:write,user:read
  uphold_api_uri: "https://uphold-api.example.com"
  uphold_dashboard_url: "https://sandbox.example.com/dashboard"
  # Social media links
  bat_medium_url: "https://medium.com/@attentiontoken"
  bat_twitter_url: "https://twitter.com/@attentiontoken"
  bat_reddit_url: "https://www.reddit.com/r/BATProject/"
  bat_rocketchat_url: "https://basicattentiontoken.rocket.chat/"
  max_site_age: 6
  should_send_notifications: true
  # Sendgrid
  # a real api_key is needed for recording new VCR based tests
  sendgrid_api_offline: true
  sendgrid_api_key: <%= ENV["SENDGRID_API_KEY"] || "fakeapikey" %>
  sendgrid_publishers_list_id: 3648346
  slack_webhook_url: false

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default

staging:
  <<: *default
